spring:
  application:
    name: ems-reactive

  config:
    import: "vault:"

  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.icx5rZCjvnkAOnqInOa5si8g
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: application

  data:
    mongodb:
      uri: mongodb://mongouser:mongopassword@localhost:27017/emsDB

  main:
    web-application-type: reactive

server:
  port: 8080
  reactive:
    context-path: /ems

github:
  token: ${github.token}
  owner: poojasheela
  repo: ems
  workflowFileName: build.yml
  ref: main

  
