spring:
  application:
    name: ems-reactive

  cloud:
    vault:
      uri: http://localhost:8200
      token: myroot
      kv:
        enabled: true
        backend: secret

  data:
    mongodb:
      uri: mongodb://mongouser:mongopassword@localhost:27017/emsDB
  main:
    web-application-type: reactive

server:
  port: 8080
  reactive:
    context-path: /ems

randomuser:
  base-url: https://randomuser.me/api
  enabled: true

github:
  token: ${github.token}
  owner: poojasheela
  repo: ems
  workflowFileName: build.yml
  ref: main
